services:
  postgres-main:
    image: postgres:15-alpine
    container_name: postgres-main
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gtu_main_db
    networks:
      - shared_network

  postgres-users:
    image: postgres:15-alpine
    container_name: postgres-users
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gtu_users_db
    networks:
      - shared_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    driver: bridge
