apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operational
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-operational
  template:
    metadata:
      labels:
        app: postgres-operational
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "operational_db"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-operational
spec:
  selector:
    app: postgres-operational
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
